export enum HealthFoodAppCategory {
  BREAKFAST = 'Breakfast',
  LUNCH = 'Lunch',
  DINNER = 'Dinner',
  SNACKS = 'Snacks',
  DESSERTS = 'Desserts',
  SMOOTHIES = 'Smoothies',
  JUICES = 'Juices',
  SOUPS = 'Soups',
  SALADS = 'Salads',
  BOWLS = 'Bowls',
  
  RAW = 'Raw',
  STEAMED = 'Steamed',
  GRILLED = 'Grilled',
  BAKED = 'Baked',
  ROASTED = 'Roasted',
  FERMENTED = 'Fermented',
  
  QUICK_MEALS = 'Quick Meals',
  MEAL_PREP = 'Meal Prep',
  PARTY_FOOD = 'Party Food',
  HOLIDAY_SPECIAL = 'Holiday Special',
  
  SUPERFOODS = 'Superfoods',
  SEASONAL_INGREDIENTS = 'Seasonal Ingredients',
  PLANT_BASED = 'Plant Based',
  WHOLE_GRAINS = 'Whole Grains',
  HEALTHY_FATS = 'Healthy Fats',
  LEAN_PROTEINS = 'Lean Proteins',
  
  TOP_FOODS = 'Top Foods',
  TOP_SNACKS = 'Top Snacks',
  TOP_BREAKFASTS = 'Top Breakfasts',
  TOP_DESSERTS = 'Top Desserts',
  
  MEAL_PLANS = 'Meal Plans',
  WEEKLY_MENUS = 'Weekly Menus',
  BATCH_COOKING = 'Batch Cooking',
  FAMILY_MEALS = 'Family Meals',
  
  HEALTHY_TIPS = 'Healthy Tips',
  COOKING_TIPS = 'Cooking Tips',
  GROCERY_GUIDES = 'Grocery Guides',
  FOOD_STORAGE = 'Food Storage',
  
  KETO_DIET = 'Keto Diet',
  VEGAN_DIET = 'Vegan Diet',
  VEGETARIAN_DIET = 'Vegetarian Diet',
  GLUTEN_FREE_DIET = 'Gluten Free Diet',
  PALEO_DIET = 'Paleo Diet',
  MEDITERRANEAN_DIET = 'Mediterranean Diet',
  LOW_CARB_DIET = 'Low Carb Diet',
  HIGH_PROTEIN = 'High Protein',
  DAIRY_FREE = 'Dairy Free',
  SUGAR_FREE = 'Sugar Free',
  
  HEALTHY_DRINKS = 'Healthy Drinks',
  ENERGY_BOOSTERS = 'Energy Boosters',
  IMMUNE_SUPPORT = 'Immune Support',
  
  KIDS_FOOD = 'Kids Food',
  ON_THE_GO = 'On The Go',
  BUDGET_FRIENDLY = 'Budget Friendly',
  GUT_HEALTH = 'Gut Health',
  ANTI_INFLAMMATORY = 'Anti-inflammatory',
  DETOX = 'Detox',
}
